# Generated by Django 2.1.7 on 2019-03-27 11:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail_localize.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0006_delete_language_model'),
        ('breads', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadingredient',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='breadingredient',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='breadpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='breadpage',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='breadsindexpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='breadsindexpage',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='breadtype',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='breadtype',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='country',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
