# Generated by Django 2.1.7 on 2019-03-14 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0001_initial'),
        ('breads', '0004_auto_20190314_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadingredient',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='breadpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='breadsindexpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='breadtype',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='breadpage',
            unique_together={('translation_key', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='breadsindexpage',
            unique_together={('translation_key', 'language')},
        ),
    ]
