# Generated by Django 2.1.7 on 2019-03-25 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail_i18n.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0004_locale'),
        ('breads', '0005_auto_20190325_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadingredient',
            name='language',
        ),
        migrations.RemoveField(
            model_name='breadtype',
            name='language',
        ),
        migrations.RemoveField(
            model_name='country',
            name='language',
        ),
        migrations.AddField(
            model_name='breadingredient',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='breadpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='breadsindexpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='breadtype',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='country',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='breadingredient',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='breadpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='breadsindexpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='breadtype',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='breadpage',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='breadpage',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.RemoveField(
            model_name='breadsindexpage',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='breadsindexpage',
            unique_together={('translation_key', 'locale')},
        ),
    ]
