# Generated by Django 2.1.15 on 2020-07-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0008_auto_20200518_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadingredient',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='breadingredient',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='breadpage',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='breadpage',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='breadsindexpage',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='breadsindexpage',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='breadtype',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='breadtype',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
    ]
