# Generated by Django 2.1.7 on 2019-03-14 17:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail_i18n.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0001_initial'),
        ('blog', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='language',
            field=models.ForeignKey(default=wagtail_i18n.models.Language.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Language'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='language',
            field=models.ForeignKey(default=wagtail_i18n.models.Language.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Language'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='blogpeoplerelationship',
            name='language',
            field=models.ForeignKey(default=wagtail_i18n.models.Language.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Language'),
        ),
        migrations.AddField(
            model_name='blogpeoplerelationship',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
