# Generated by Django 2.1.7 on 2019-03-27 11:10

from django.db import migrations
from wagtail_i18n.bootstrap import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_wagtail_i18n_1'),
    ]

    operations = [
        BootstrapTranslatableModel('blog.BlogIndexPage'),
        BootstrapTranslatableModel('blog.BlogPage'),
        BootstrapTranslatableModel('blog.BlogPeopleRelationship'),
    ]
