# Generated by Django 2.1.7 on 2019-03-27 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0002_initial_data'),
        ('blog', '0005_wagtail_localize_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='blogpeoplerelationship',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='blogindexpage',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='blogpage',
            unique_together={('translation_key', 'locale')},
        ),
    ]
