# Generated by Django 2.1.12 on 2019-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_wagtail_localize_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpeoplerelationship',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
    ]
