# Generated by Django 2.1.7 on 2019-03-27 11:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail_localize.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0002_initial_data'),
        ('locations', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='locationsindexpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AddField(
            model_name='locationsindexpage',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='locationoperatinghours',
            name='closed',
            field=models.BooleanField(blank=True, help_text='Tick if location is closed on this day', verbose_name='Closed?'),
        ),
    ]
