# Generated by Django 2.1.7 on 2019-03-14 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0001_initial'),
        ('locations', '0004_auto_20190314_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='locationsindexpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='locationpage',
            unique_together={('translation_key', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='locationsindexpage',
            unique_together={('translation_key', 'language')},
        ),
    ]
