# Generated by Django 2.1.7 on 2019-03-27 11:10

from django.db import migrations
from wagtail_localize.bootstrap import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_wagtail_localize_1'),
    ]

    operations = [
        BootstrapTranslatableModel('locations.LocationsIndexPage'),
        BootstrapTranslatableModel('locations.LocationPage'),
    ]
