# Generated by Django 2.1.7 on 2019-03-27 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_localize', '0002_initial_data'),
        ('locations', '0005_wagtail_localize_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='locationsindexpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='locationpage',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='locationsindexpage',
            unique_together={('translation_key', 'locale')},
        ),
    ]
