# Generated by Django 2.1.12 on 2019-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_regionflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locationsindexpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
    ]
