# Generated by Django 2.1.7 on 2019-03-14 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0001_initial'),
        ('base', '0005_auto_20190314_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('translation_key', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='formpage',
            unique_together={('translation_key', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='gallerypage',
            unique_together={('translation_key', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='homepage',
            unique_together={('translation_key', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='standardpage',
            unique_together={('translation_key', 'language')},
        ),
    ]
