# Generated by Django 2.1.7 on 2019-03-27 11:10

from django.db import migrations
from wagtail_i18n.bootstrap import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_wagtail_i18n_1'),
    ]

    operations = [
        BootstrapTranslatableModel('base.FooterText'),
        BootstrapTranslatableModel('base.FormField'),
        BootstrapTranslatableModel('base.FormPage'),
        BootstrapTranslatableModel('base.GalleryPage'),
        BootstrapTranslatableModel('base.HomePage'),
        BootstrapTranslatableModel('base.StandardPage'),
    ]
