# Generated by Django 2.1.7 on 2019-03-25 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail_i18n.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0004_locale'),
        ('base', '0006_auto_20190325_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='language',
        ),
        migrations.RemoveField(
            model_name='people',
            name='language',
        ),
        migrations.AddField(
            model_name='footertext',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='people',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='footertext',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='formpage',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='gallerypage',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='homepage',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='standardpage',
            unique_together={('translation_key', 'locale')},
        ),
    ]
