# Generated by Django 2.1.15 on 2020-07-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200518_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='footertext',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='people',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='is_source_translation',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='locale',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
    ]
